# Generated by Django 2.0.4 on 2019-01-10 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=512)),
                ('slug', models.SlugField(max_length=512)),
                ('date', models.DateField()),
                ('text', models.TextField()),
                ('translated_text', models.TextField()),
            ],
        ),
    ]
