# Generated by Django 2.0.4 on 2019-01-22 01:24

from django.db import migrations, models
import django.db.models.deletion
import translate_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher', models.CharField(default='nytimes', max_length=128)),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=512, unique=True)),
                ('slug', models.SlugField(max_length=512)),
                ('date', models.DateField(auto_now=True)),
                ('text', models.TextField()),
                ('translated_text', models.TextField()),
                ('section', models.CharField(max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, upload_to=translate_app.models.user_directory_path)),
                ('caption', models.CharField(max_length=512, null=True)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='translate_app.Article')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=128)),
                ('article', models.ManyToManyField(to='translate_app.Article')),
            ],
        ),
    ]
