# Generated by Django 2.0.4 on 2019-01-12 22:35

from django.db import migrations, models
import translate_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('translate_app', '0002_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=512, unique=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='picture',
            field=models.ImageField(blank=True, upload_to=translate_app.models.user_directory_path),
        ),
    ]
