# Generated by Django 2.0.4 on 2019-01-12 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translate_app', '0003_auto_20190112_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=512),
        ),
    ]
