# Generated by Django 2.0.4 on 2019-02-13 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translate_app', '0003_articlewords'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='subtitle',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='translated_text',
            field=models.TextField(null=True),
        ),
    ]
