# Generated by Django 2.0.4 on 2019-01-13 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translate_app', '0004_auto_20190112_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=512, unique=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='caption',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
