# Generated by Django 2.0.4 on 2019-01-13 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translate_app', '0005_auto_20190112_2015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='publisher',
            field=models.CharField(default='nytimes', max_length=128),
        ),
        migrations.AddField(
            model_name='tag',
            name='article',
            field=models.ManyToManyField(to='translate_app.Article'),
        ),
    ]
