# Generated by Django 2.0.4 on 2019-01-13 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translate_app', '0007_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='article',
        ),
        migrations.AddField(
            model_name='article',
            name='section',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
